<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4F12GA8" failures="1" tests="4" name="listenerStudy.Myclass2" time="0.066" errors="0" timestamp="2024-08-02T12:50:37 IST" skipped="0">
  <testcase classname="listenerStudy.Myclass2" name="g" time="0.057">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listenerStudy.Myclass2.g(Myclass2.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[ TC gexecution started
TCgfailed]]>
    </system-out>
  </testcase> <!-- g -->
  <testcase classname="listenerStudy.Myclass2" name="e" time="0.004">
    <system-out>
      <![CDATA[ TC eexecution started
e is running
TCecompleted duccessfully]]>
    </system-out>
  </testcase> <!-- e -->
  <testcase classname="listenerStudy.Myclass2" name="h" time="0.003">
    <system-out>
      <![CDATA[ TC hexecution started
h is running
TChcompleted duccessfully]]>
    </system-out>
  </testcase> <!-- h -->
  <testcase classname="listenerStudy.Myclass2" name="f" time="0.002">
    <system-out>
      <![CDATA[ TC fexecution started
 f is rnning
TCfcompleted duccessfully]]>
    </system-out>
  </testcase> <!-- f -->
  <system-out>
    <![CDATA[ TC gexecution started
TCgfailed
 TC hexecution started
h is running
TChcompleted duccessfully
 TC eexecution started
e is running
TCecompleted duccessfully
 TC fexecution started
 f is rnning
TCfcompleted duccessfully]]>
  </system-out>
</testsuite> <!-- listenerStudy.Myclass2 -->
